# File:   Makefile
# Author: M. P. Hayes, UCECE
# Date:   12 Sep 2010
# Descr:  Makefile for game

# Definitions.
CC = gcc
SRC = ./src/test
UCFK = ..
CFLAGS = -Wall -Wstrict-prototypes -Wextra -I$(SRC) -g
DEL = rm


# Default target.
all:
	$(CC) $(CFLAGS) -o test.o $(SRC)/test.c $(SRC)/../tetris.c $(SRC)/../physics.c